<?php

// Malayalam translation for schemes
return [
    'scheme_title_1' => 'Fixed Payment Scheme',
    'scheme_title_2' => 'Flexible Payment Scheme',
    'scheme_title_3' => 'Easy Gold Scheme',

    'payment_terms' => 'Duration of all schemes is 11 months. Payments are due on a monthly basis, and to keep the package active, customers must make their monthly payments between the 1st and 5th of each month. If payment is not received by the 5th, the package will get terminated, and the customer will no longer be eligible to continue the scheme. If the package gets terminated due to non-payment of installment in time, the total amount remitted so far could be withdrawn at the end of the maturation period of the scheme in cash or gold, without any offer.',

    'scheme_description_1' => 'Duration of Fixed Payment Scheme is 11 months. 
    ● In this fixed monthly payment plan, the payment amount is set and remains consistent each month.
    ● In the 12th month, users can purchase gold jewelry free of making charges from Madhurima Gold and Diamonds (designs include Kolkata, Turkish, Bombay, Kerala, Nagas, and more). 
    ● Customers can pay between Rs 500 and Rs 500,000 per month (in multiples of 500). 
    ● The initial installment paid must remain consistent throughout the scheme. For example, if the first installment is Rs 10,000, the same amount applies to all subsequent months. 
    ● If installments are not paid before the 5th of each month, the package will get terminated and the customers will lose the privilege to avail offers. The total amount remitted so far could be withdrawn in cash or as gold purchases at the end of the scheme period on the 12th month without any offers. 
    ● Payments must be made exclusively through the Madhurima Gold and Diamonds app for security and transparency. 
    ● Gold rates will be based on the "current rates" at the end of the scheme period (12th month). 
    ● All disputes will be resolved under the jurisdiction of Kozhikode District Court. Current tax and revenue policies are applicable.',

    'scheme_description_2' => 'Duration of Flexible Payment Scheme is 11 months. 
    ● The monthly installment amount is flexible and can be determined by the user for the first the 6 months. From the 7th month, the installment will be fixed based on the median of all amounts paid in the first six months. For example, if the total amount is Rs 50,000, the installment cannot exceed Rs 8,333 but can be less. 
    ● In the 12th month, users can purchase gold jewelry free of making charges from Madhurima Gold and Diamonds (designs include Kolkata, Turkish, Bombay, Kerala, Nagas, and more).
    ● If installments are not paid before the 5th of each month, the package will get terminated and the customers will lose the privilege to avail offers. The total amount remitted so far could be withdrawn in cash or as gold purchases at the end of the scheme period on the 12th month without any offers.
    ● Payments must be made exclusively through the Madhurima Gold and Diamonds app for security and transparency. 
    ● Gold rates will be based on the "current rates" at the end of the scheme (12th month). 
    ● All disputes will be resolved under the jurisdiction of Kozhikode District Court. Current tax and revenue policies are applicable.',

    'scheme_description_3' => 'Duration of Easy Gold Scheme is 11 months. 
    ● The monthly installment amount is flexible and can be determined for the first 6 months. From the 7th month, the installment will be fixed based on the median of all amounts paid in the first six months. For example, if the total amount is Rs 50,000, the installment cannot exceed Rs 8,333 but can be less. The amount remitted on each month will be converted into gold based on the current gold rate of the date of payment. 
    ● In the 12th month, users can purchase gold jewelry free of making charges from Madhurima Gold and Diamonds (designs include Kolkata, Turkish, Bombay, Kerala, Nagas, and more).
    ● Each Installment amounts will reflect current gold rates on the day of payment. 
    ● If installments are not paid before the 5th of each month, the package will get terminated and the customers will lose the privilege to avail offers. The total amount remitted so far could be withdrawn in cash or as gold purchases at the end of the scheme period on the 12th month without any offers.
    ● Payments must be made exclusively through the Madhurima Gold and Diamonds app for security and transparency. 
    ● Gold rates will be based on the "current rates" at the end of the scheme (12th month). 
    ● All disputes will be resolved under the jurisdiction of Kozhikode District Court. Current tax and revenue policies are applicable.',

    'terms_and_condition_1' => 'These Terms and Conditions govern the use of the "Madhurima Gold & Diamonds App" (“Mobile Application” or “Service”) and any of its related products and services (collectively, “Services”), developed and provided by Madhurima Gold and Diamonds (with address 59/2 Railway Station Road, Mele Palayam, Kozhikode, PIN - 673001) (“hereinafter referred to as "Madhurima Gold & Diamonds" or "we" or "us", or "our"). 
Acceptance of Terms
By accessing, downloading, installing, or using the App, you (hereinafter referred to as the "User" or "you") agree to be bound by these Terms and Conditions. If you do not agree to these Terms and Conditions, please do not download, install, or use the App. By accessing and using the Mobile Application and Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement. You acknowledge that this Agreement is a legally binding contract between you and Madhurima Gold & Diamonds, even though executed electronically and not signed by you.
Table of contents
Accounts and membership
Prohibited uses
Payments
Severability
Dispute resolution
Changes and amendments
Contacting us

Accounts and membership
You must be at least 18 years of age to use the Mobile Application and Services. By using the Mobile Application and Services and by agreeing to this Agreement you warrant and represent that you are at least 18 years of age. If you create an account in the Mobile Application, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. We may monitor and review new accounts before you sign in and start using the Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. We may suspend, disable, or delete your account (or any part thereof) if we determine that you have violated any provision of this Agreement or that your conduct or content would tend to damage our reputation and goodwill. If we delete your account for the foregoing reasons, you may not re-register for our Services. We may block your email address and Internet protocol address to prevent further registration.
Prohibited uses
In addition to other terms as set forth in the Agreement, you are prohibited from using the Mobile Application and Services or Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Mobile Application and Services, third party products and services, or the Internet; (h) to spam, phish, pharm, pretext, spider, crawl, or scrape; (i) for any obscene or immoral purpose; or (j) to interfere with or circumvent the security features of the Mobile Application and Services, third party products and services, or the Internet. We reserve the right to terminate your use of the Mobile Application and Services for violating any of the prohibited uses.
Payments
Payments to the app should be made only through Razor Pay payment gateway; users can make the payment using debit cards, credit cards, UPI, or any other methods specified in the gateway. Our valuable users should make the payment on or before the 5th of every month. In the failure of such obligations, the subscribers of schemes would be compelled to follow whatever terms and conditions the respected schemes have to offer. 
Severability
All rights and restrictions contained in this Agreement may be exercised and shall be applicable and binding only to the extent that they do not violate applicable laws and are intended to be limited to the extent necessary so that they will not render this Agreement illegal, invalid or unenforceable. If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions thereof shall remain in full force and effect.
Dispute resolution
The formation, interpretation, and performance of this Agreement and any disputes arising out of it shall be governed by the substantive and procedural laws of Kerala, India without regard to its rules on conflicts or choice of law and, to the extent applicable, the laws of India. The exclusive jurisdiction and venue for actions related to the subject matter hereof shall be the District Court located in Kozhikode, Kerala, India, and you hereby submit to the personal jurisdiction of the court. You hereby waive any right to a jury trial in any proceeding arising out of or related to this Agreement. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.
Changes and amendments
We reserve the right to modify this Agreement or its terms related to the Mobile Application and Services at any time at our discretion. When we do, we will post a notification in the Mobile Application. We may also provide notice to you in other ways at our discretion, such as through the contact information you have provided.
An updated version of this Agreement will be effective immediately upon the posting of the revised Agreement unless otherwise specified. Your continued use of the Mobile Application and Services after the effective date of the revised Agreement (or such other act specified at that time) will constitute your consent to those changes.
Acceptance of these terms
You acknowledge that you have read this Agreement and agree to all its terms and conditions. By accessing and using the Mobile Application and Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to access or use the Mobile Application and Services. 
Contacting us
If you have any questions, concerns, or complaints regarding this Agreement, we encourage you to contact us using the details below:
madhurimagold@gmail.com
This document was last updated on December 12, 2024.',
    'terms_and_condition_2' => 'These terms and conditions (“Agreement”) set forth the general terms and conditions of your use of the “Madhurima Gold and Diamonds App” mobile application (“Mobile Application” or “Service”) and any of its related products and services (collectively, “Services”). This Agreement is legally binding between you (“User”, “you” or “your”) and Madhurima Gold and Diamonds (with address 59/2 Railway Station Road, Mele Palayam, Kozhikode, PIN - 673001) (“Madhurima Gold and Diamonds”, “we”, “us” or “our”). If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such an entity to this Agreement, in which case the terms “User”, “you” or “your” shall refer to such entity. If you do not have such authority, or if you do not agree with the terms of this Agreement, you must not accept this Agreement and may not access and use the Mobile Application and Services. By accessing and using the Mobile Application and Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement. You acknowledge that this Agreement is a contract between you and Madhurima Gold and Diamonds, even though it is electronic and is not physically signed by you, and it governs your use of the Mobile Application and Services.
Table of contents
Accounts and membership
Links to other resources
Prohibited uses
Payments
Severability
Dispute resolution
Changes and amendments
Acceptance of these terms
Contacting us
Accounts and membership
You must be at least 18 years of age to use the Mobile Application and Services. By using the Mobile Application and Services and by agreeing to this Agreement you warrant and represent that you are at least 18 years of age. If you create an account in the Mobile Application, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. We may monitor and review new accounts before you may sign in and start using the Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. We may suspend, disable, or delete your account (or any part thereof) if we determine that you have violated any provision of this Agreement or that your conduct or content would tend to damage our reputation and goodwill. If we delete your account for the foregoing reasons, you may not re-register for our Services. We may block your email address and Internet protocol address to prevent further registration.
Links to other resources
Although the Mobile Application and Services may link to other resources (such as websites, mobile applications, etc.), we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked resource, unless specifically stated herein. We are not responsible for examining or evaluating, and we do not warrant the offerings of any businesses or individuals or the content of their resources. We do not assume any responsibility or liability for the actions, products, services, and content of any other third parties. You should carefully review the legal statements and other conditions of use of any resource which you access through a link in the Mobile Application. Your linking to any other off-site resources is at your own risk.
Prohibited uses
In addition to other terms as set forth in the Agreement, you are prohibited from using the Mobile Application and Services or Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Mobile Application and Services, third party products and services, or the Internet; (h) to spam, phish, pharm, pretext, spider, crawl, or scrape; (i) for any obscene or immoral purpose; or (j) to interfere with or circumvent the security features of the Mobile Application and Services, third party products and services, or the Internet. We reserve the right to terminate your use of the Mobile Application and Services for violating any of the prohibited uses.
Payments
Payments to the app should be made only through Razor Pay; users can make the payment using debit cards, credit cards, UPI, or any other methods specified in the gateway. Our valuable users should make the payment on or before the 5th of every month. In the failure of such obligations, the subscribers of schemes would be compelled to follow whatever terms and conditions the respected schemes have to offer. 
Severability
All rights and restrictions contained in this Agreement may be exercised and shall be applicable and binding only to the extent that they do not violate any applicable laws and are intended to be limited to the extent necessary so that they will not render this Agreement illegal, invalid, or unenforceable. If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions thereof shall remain in full force and effect.
Dispute resolution
The formation, interpretation, and performance of this Agreement and any disputes arising out of it shall be governed by the substantive and procedural laws of Kerala, India without regard to its rules on conflicts or choice of law and, to the extent applicable, the laws of India. The exclusive jurisdiction and venue for actions related to the subject matter hereof shall be the District Court located in Kozhikode, Kerala, India, and you hereby submit to the personal jurisdiction of the court. You hereby waive any right to a jury trial in any proceeding arising out of or related to this Agreement. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.
Changes and amendments
We reserve the right to modify this Agreement or its terms related to the Mobile Application and Services at any time at our discretion. When we do, we will post a notification in the Mobile Application. We may also provide notice to you in other ways at our discretion, such as through the contact information you have provided.
An updated version of this Agreement will be effective immediately upon the posting of the revised Agreement unless otherwise specified. Your continued use of the Mobile Application and Services after the effective date of the revised Agreement (or such other act specified at that time) will constitute your consent to those changes.
Acceptance of these terms
You acknowledge that you have read this Agreement and agree to all its terms and conditions. By accessing and using the Mobile Application and Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to access or use the Mobile Application and Services. 
Contacting us
If you have any questions, concerns, or complaints regarding this Agreement, we encourage you to contact us using the details below:
madhurimagold@gmail.com
This document was last updated on December 12, 2024.',
    'terms_and_condition_3' => 'These terms and conditions (“Agreement”) set forth the general terms and conditions of your use of the “Madhurima Gold and Diamonds App” mobile application (“Mobile Application” or “Service”) and any of its related products and services (collectively, “Services”). This Agreement is legally binding between you (“User”, “you” or “your”) and Madhurima Gold and Diamonds (with address 59/2 Railway Station Road, Mele Palayam, Kozhikode, PIN - 673001) (“Madhurima Gold and Diamonds”, “we”, “us” or “our”). If you are entering into this Agreement on behalf of a business or other legal entity, you represent that you have the authority to bind such an entity to this Agreement, in which case the terms “User”, “you”, or “your” shall refer to such entity. If you do not have such authority, or if you do not agree with the terms of this Agreement, you must not accept this Agreement and may not access and use the Mobile Application and Services. By accessing and using the Mobile Application and Services, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement. You acknowledge that this Agreement is a contract between you and Madhurima Gold and Diamonds, even though it is electronic and is not physically signed by you, and it governs your use of the Mobile Application and Services.
Table of contents
Accounts and membership
Links to other resources
Prohibited uses
Payments
Severability
Dispute resolution
Changes and amendments
Contacting us

Accounts and membership
You must be at least 18 years of age to use the Mobile Application and Services. By using the Mobile Application and Services and by agreeing to this Agreement you warrant and represent that you are at least 18 years of age. If you create an account in the Mobile Application, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. We may monitor and review new accounts before you may sign in and start using the Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. We may suspend, disable, or delete your account (or any part thereof) if we determine that you have violated any provision of this Agreement or that your conduct or content would tend to damage our reputation and goodwill. If we delete your account for the foregoing reasons, you may not re-register for our Services. We may block your email address and Internet protocol address to prevent further registration.
Links to other resources
Although the Mobile Application and Services may link to other resources (such as websites, mobile applications, etc.), we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked resource, unless specifically stated herein. We are not responsible for examining or evaluating, and we do not warrant the offerings of any businesses or individuals or the content of their resources. We do not assume any responsibility or liability for the actions, products, services, and content of any other third parties. You should carefully review the legal statements and other conditions of use of any resource which you access through a link in the Mobile Application. Your linking to any other off-site resources is at your own risk.
Prohibited uses
In addition to other terms as set forth in the Agreement, you are prohibited from using the Mobile Application and Services or Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Mobile Application and Services, third party products and services, or the Internet; (h) to spam, phish, pharm, pretext, spider, crawl, or scrape; (i) for any obscene or immoral purpose; or (j) to interfere with or circumvent the security features of the Mobile Application and Services, third party products and services, or the Internet. We reserve the right to terminate your use of the Mobile Application and Services for violating any of the prohibited uses.
Payments
Payments to the app should be made only through Razor Pay; users can make the payment using debit cards, credit cards, UPI, or any other methods specified in the gateway. Our valuable users should make the payment on or before the 5th of every month. In the failure of such obligations, the subscribers of schemes would be compelled to follow whatever terms and conditions the respected schemes have to offer. 
Severability
If any provision of these Terms and Conditions is found to be invalid or unenforceable, such provision shall be deemed severed from these Terms and Conditions and shall not affect the validity and enforceability of the remaining provisions.
Dispute resolution
The formation, interpretation, and performance of this Agreement and any disputes arising out of it shall be governed by the substantive and procedural laws of Kerala, India without regard to its rules on conflicts or choice of law and, to the extent applicable, the laws of India. The exclusive jurisdiction and venue for actions related to the subject matter hereof shall be the District Court located in Kozhikode, Kerala, India, and you hereby submit to the personal jurisdiction of the court. You hereby waive any right to a jury trial in any proceeding arising out of or related to this Agreement. The United Nations Convention on Contracts for the International Sale of Goods does not apply to this Agreement.
Changes and amendments
We reserve the right to modify this Agreement or its terms related to the Mobile Application and Services at any time at our discretion. When we do, we will post a notification in the Mobile Application. We may also provide notice to you in other ways at our discretion, such as through the contact information you have provided.
An updated version of this Agreement will be effective immediately upon the posting of the revised Agreement unless otherwise specified. Your continued use of the Mobile Application and Services after the effective date of the revised Agreement (or such other act specified at that time) will constitute your consent to those changes.
Contacting us
If you have any questions, concerns, or complaints regarding this Agreement, we encourage you to contact us using the details below:
madhurimagold@gmail.com
This document was last updated on December 12, 2024.',
];
